#!/usr/bin/perl
 use IO::Socket;
 use Net::hostent;
 print "This is the Universal Port Opening Daemon\n";
 print "-----------------------------------------\n";
 if ($ARGV[0] eq "") { help(); };

 $PORT = $ARGV[0];                  

 $server = IO::Socket::INET->new( Proto     => 'tcp',
                                  LocalPort => $PORT,
                                  Listen    => SOMAXCONN,
                                  Reuse     => 1);

 die "can't setup server" unless $server;
 print "[port $PORT accepting clients]\n";
 our $jimmy;
 while ($client = $server->accept()) {
   our $mrh;
   our $curip;
   our $hostinfo;
   open LOG, ">>out.log" or die $!;
   $client->autoflush(1);
   $hostinfo = gethostbyaddr($client->peeraddr);
   die "a name resolution failed!" unless $hostinfo->addr;
   $curip = inet_ntoa($hostinfo->addr);
   if ($mrh ne $curip) { print LOG $curip, "\n"; };
   if ($mrh ne $curip) { $jimmy++; };
   printf "[Connect $jimmy from %s]\n", inet_ntoa($hostinfo->addr);
   print $client "Welcome, Now get out! You're Visiter $jimmy\n";  
   close $client;
   $mrh = inet_ntoa($hostinfo->addr);
 }

sub help {
	print "upod v.CVS\n";
	print "syntax: upod [port]\n";
	print "For more help see the man page or web site\n";
	exit;
};
