// -*- C++ -*- generated by wxGlade 0.4.1 on Sat Mar 11 11:30:15 2006

#include "randd.h"

 IMPLEMENT_APP(MainApp) // Initializes the MainApp class and tells our program
 // to run it
bool MyApp::OnInit()
{
    wxInitAllImageHandlers();
    MyFrame* frame_4 = new MyFrame(0, -1, wxT(""));
    SetTopWindow(frame_4);
    frame_4->Show();
    return true;
}

MyFrame::MyFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxFrame(parent, id, title, pos, size, wxDEFAULT_FRAME_STYLE)
{
    // begin wxGlade: MyFrame::MyFrame
    Stats = CreateStatusBar(2, 0);
    label_8 = new wxStaticText(this, -1, wxT("Paper Progs Random 06"));
    label_6 = new wxStaticText(this, -1, wxT("Player 1 Guess:"));
    text_ctrl_3 = new wxTextCtrl(this, -1, wxT(""));
    label_7 = new wxStaticText(this, -1, wxT("9"));
    label_5_copy = new wxStaticText(this, -1, wxT("Player 2 Guess:"));
    text_ctrl_4 = new wxTextCtrl(this, -1, wxT(""));
    button_1 = new wxButton(this, -1, wxT("Play Random!"));

    set_properties();
    do_layout();
    // end wxGlade
}


BEGIN_EVENT_TABLE(MyFrame, wxFrame)
    // begin wxGlade: MyFrame::event_table
    EVT_BUTTON(-1, MyFrame::genrand)
    // end wxGlade
END_EVENT_TABLE();


void MyFrame::genrand(wxCommandEvent &event)
{
    event.Skip();
}


// wxGlade: add MyFrame event handlers


void MyFrame::set_properties()
{
    // begin wxGlade: MyFrame::set_properties
    SetTitle(wxT("Random Number Generator 06"));
    int Stats_widths[] = { -1, 30 };
    Stats->SetStatusWidths(2, Stats_widths);
    const wxString Stats_fields[] = {
        wxT("Winage"),
        wxT("Number gened")
    };
    for(int i = 0; i < Stats->GetFieldsCount(); ++i) {
        Stats->SetStatusText(Stats_fields[i], i);
    }
    label_8->SetFont(wxFont(15, wxDEFAULT, wxSLANT, wxNORMAL, 0, wxT("")));
    label_7->SetBackgroundColour(wxColour(241, 239, 235));
    label_7->SetForegroundColour(wxColour(0, 0, 0));
    label_7->SetFont(wxFont(42, wxDEFAULT, wxNORMAL, wxNORMAL, 0, wxT("")));
    // end wxGlade
}


void MyFrame::do_layout()
{
    // begin wxGlade: MyFrame::do_layout
    wxBoxSizer* sizer_4 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_6 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_9 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_8 = new wxBoxSizer(wxVERTICAL);
    sizer_4->Add(label_8, 0, wxALIGN_CENTER_HORIZONTAL|wxADJUST_MINSIZE, 0);
    sizer_8->Add(label_6, 0, wxADJUST_MINSIZE, 0);
    sizer_8->Add(text_ctrl_3, 0, wxADJUST_MINSIZE, 0);
    sizer_6->Add(sizer_8, 1, wxEXPAND, 0);
    sizer_6->Add(label_7, 0, wxADJUST_MINSIZE, 0);
    sizer_9->Add(label_5_copy, 0, wxALIGN_RIGHT|wxADJUST_MINSIZE, 0);
    sizer_9->Add(text_ctrl_4, 0, wxALIGN_RIGHT|wxADJUST_MINSIZE, 0);
    sizer_6->Add(sizer_9, 1, wxEXPAND, 0);
    sizer_4->Add(sizer_6, 1, wxEXPAND, 0);
    sizer_4->Add(button_1, 0, wxEXPAND|wxALIGN_CENTER_VERTICAL, 0);
    SetAutoLayout(true);
    SetSizer(sizer_4);
    sizer_4->Fit(this);
    sizer_4->SetSizeHints(this);
    Layout();
    Centre();
    // end wxGlade
}

