// -*- C++ -*- generated by wxGlade 0.4.1 on Sat Mar 11 11:46:00 2006

#include <iostream>
#include "rand.h"



MyFrame::MyFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxFrame(parent, id, title, pos, size, wxDEFAULT_FRAME_STYLE)
{
    srand((unsigned)time(0));
       wxPanel* panel = new wxPanel(this, -1);
    // begin wxGlade: MyFrame::MyFrame
    Stats = CreateStatusBar(2, 0);
           SetBackgroundColour(panel->GetBackgroundColour());
    label_8 = new wxStaticText(this, -1, wxT("Paper Progs Random 06"));
       SetBackgroundColour(panel->GetBackgroundColour());
    label_6 = new wxStaticText(this, -1, wxT("Player 1 Guess:"));
       SetBackgroundColour(panel->GetBackgroundColour());
    text_ctrl_3 = new wxTextCtrl(this, -1, wxT(""));
       SetBackgroundColour(panel->GetBackgroundColour());
    label_7 = new wxStaticText(this, -1, wxT("    "));
           SetBackgroundColour(panel->GetBackgroundColour());
    label_5_copy = new wxStaticText(this, -1, wxT("Player 2 Guess:"));
       SetBackgroundColour(panel->GetBackgroundColour());
    text_ctrl_4 = new wxTextCtrl(this, -1, wxT(""));
    button_1 = new wxButton(this, -1, wxT("Play Numgen!"));

    set_properties();
    do_layout();
    // end wxGlade
}


BEGIN_EVENT_TABLE(MyFrame, wxFrame)
    // begin wxGlade: MyFrame::event_table
    EVT_BUTTON(-1, MyFrame::genrand)
    // end wxGlade
END_EVENT_TABLE();


void MyFrame::genrand(wxCommandEvent &event)
{
            wxPanel* panel = new wxPanel(this, -1);
   int random_int;
   long numy;
   long numy2;
   random_int = (rand()%10)+1; 
   wxString mynewstring = wxString::Format(wxT("%d"), random_int);
   Stats->SetStatusText(mynewstring, 1);
   label_7->SetLabel(mynewstring);
   wxString test = text_ctrl_3->GetValue();
   numy = wxAtoi(test);
   wxString test2 = text_ctrl_4->GetValue();
   numy2 = wxAtoi(test2);
   if (numy2 == numy)
		Stats->SetStatusText(wxT("Choose Different Numbers"));
   else if (numy == random_int)
		Stats->SetStatusText(wxT("Player 1 Wins"));
   else if (numy2 == random_int)
		Stats->SetStatusText(wxT("Player 2 Wins"));
   else { Stats->SetStatusText(wxT("You all lose!"));}
}


// wxGlade: add MyFrame event handlers


void MyFrame::set_properties()
{
            wxPanel* panel = new wxPanel(this, -1);
    // begin wxGlade: MyFrame::set_properties
    SetTitle(wxT("Numgen 2006 XP edition"));
    int Stats_widths[] = { -1, 30 };
    Stats->SetStatusWidths(2, Stats_widths);
    const wxString Stats_fields[] = {
        wxT("Winage"),
        wxT("Number gened")
    };
    for(int i = 0; i < Stats->GetFieldsCount(); ++i) {
        Stats->SetStatusText(Stats_fields[i], i);
    }
    label_8->SetFont(wxFont(15, wxDEFAULT, wxSLANT, wxNORMAL, 0, wxT("")));
    label_7->SetFont(wxFont(42, wxROMAN, wxNORMAL, wxNORMAL, 0, wxT("")));
    // end wxGlade
}


void MyFrame::do_layout()
{
    // begin wxGlade: MyFrame::do_layout
           wxPanel* panel = new wxPanel(this, -1);
           SetBackgroundColour(panel->GetBackgroundColour());
    wxBoxSizer* sizer_4 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_6 = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_9 = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_8 = new wxBoxSizer(wxVERTICAL);
    sizer_4->Add(label_8, 0, wxALIGN_CENTER_HORIZONTAL|wxADJUST_MINSIZE, 0);
    sizer_8->Add(label_6, 0, wxADJUST_MINSIZE, 0);
    sizer_8->Add(text_ctrl_3, 0, wxADJUST_MINSIZE, 0);
    sizer_6->Add(sizer_8, 1, wxEXPAND, 0);
    sizer_6->Add(label_7, 0, wxALIGN_CENTER_HORIZONTAL|wxADJUST_MINSIZE, 0);
    sizer_9->Add(label_5_copy, 0, wxALIGN_RIGHT|wxADJUST_MINSIZE, 0);
    sizer_9->Add(text_ctrl_4, 0, wxALIGN_RIGHT|wxADJUST_MINSIZE, 0);
    sizer_6->Add(sizer_9, 1, wxEXPAND, 0);
    sizer_4->Add(sizer_6, 1, wxEXPAND, 0);
    sizer_4->Add(button_1, 0, wxEXPAND|wxALIGN_CENTER_VERTICAL, 0);
    SetAutoLayout(true);
    SetSizer(sizer_4);
    sizer_4->Fit(this);
    sizer_4->SetSizeHints(this);
    Layout();
    Centre();
    // end wxGlade
}



class MyApp: public wxApp {
public:
    bool OnInit();
};

IMPLEMENT_APP(MyApp)

bool MyApp::OnInit()
{
    MyFrame* frame_4 = new MyFrame(0, -1, wxT(""));
    SetTopWindow(frame_4);
    frame_4->Show();
    return true;
}
