#!/usr/bin/perl
#    Copyright (C) 2005 John Lockman
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA


#use Mail::Client::Yahoo;
use Net::SMTP;
use Mail::Webmail::Gmail;

print "Welcome to the CVS PaperMail\n";
#Ok, so this is a mess right now!... But it's CVS so, i'll fix it later

sub ymail {
$y = Mail::Client::Yahoo->login(
  username => '',
  password => '',
);

$y->send_message(
  to => 'ultramancool@gmail.com' ,
  subject => 'test' ,
  body => 'papermail' ,
);
};

sub smtp {
    $smtp = Net::SMTP->new('');
    $smtp->mail($ENV{USER});
    $smtp->to('');
    $smtp->data();
    $smtp->datasend("To: ultramancool@shinyfeet.com\n");
    $smtp->datasend("\n");
    $smtp->datasend("A simple test message\n");
    $smtp->dataend();
    $smtp->quit;
};

sub gmail {
	print "Enter Gmail Username\n";
	my $gmailuser = <STDIN>;
	print "Enter Gmail Password\n";
	my $gmaillpass = <STDIN>;
	my $gmail = Mail::Webmail::Gmail->new(username => $gmailuser, password	=> $gmaillpass,);
	my $email_addrs = [
	   'pufflez@gmail.com',
	   'ultramancool@gmail.com'
	   ];
	for $i (1...100) {
	$gmail->send_message( to => $email_addrs, subject => "Sent Via Papermail $i", msgbody => 'Yippe PaperMail well 	atleast not you cant say you dont have enought mail!' );
};
};
